site_name: NI SystemLink Operations Handbook
repo_url: https://github.com/ni/systemlink-operations-handbook
copyright: Copyright Â© 2020 National Instruments Corporation

docs_dir: handbook
edit_uri: edit/master/handbook/
strict: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
      marker: ''

plugins:
  - awesome-pages:
      collapse_single_pages: true
      strict: true
  - enumerate-headings:
      toc_depth: 4
  - git-revision-date-localized
  - search

theme:
  custom_dir: overrides
  favicon: img/favicon.ico
  font: false
  icon:
    logo: NI/SystemLink
  name: material
  palette:
    scheme: ni

extra_css:
  - stylesheets/extra.css


nav:
  - 'README.md'
  - 'placeholder/README.md'
  - 'openid-connect/openid-connect.md'